---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: flaresolverr
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: flaresolverr/flaresolverr
      tag: v1.2.3
      pullPolicy: Always
    env:
      TZ: "Europe/Brussels"
      LOG_LEVEL: "info"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 3000Mi

