---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: entertainment 
spec:
  interval: 5m
  chart:
    spec:
      chart: lidarr
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v3.0.4.1132
    env:
      TZ: "Europe/Brussels"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: letsencrypt 
      hosts:
      - host: lidarr.lab.kharnox.xyz
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - lidarr.lab.kharnox.xyz
        secretName: lidarr-tls
