---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseer
  namespace: entertainment
spec:
  interval: 5m
  chart:
    spec:
      chart: overseerr
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: sctx/overseerr
      tag: 1.20.1
      pullPolicy: Always
    env:
      TZ: "Europe/Brussels"
      LOG_LEVEL: "info"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - host: overseerr.lab.kharnox.xyz
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "overseerr.lab.kharnox.xyz"
        secretName: overseerr-tls
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: "20Gi"
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi