---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: entertainment
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.3
    env:
      TZ: "Europe/Brussels"
    service:
      additionalServices:
      - enabled: true
        nameSuffix: bittorrent
        type: LoadBalancer
        externalIPs:
        - 10.0.1.180
        port:
          port: 50413
          name: bittorrent
          protocol: TCP
          targetPort: 6881
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: letsencrypt 
      hosts:
      - host: qbittorrent.lab.kharnox.xyz
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - qbittorrent.lab.kharnox.xyz
        secretName: qbittorrent-tls
    persistence:
      config:
        enabled: true 
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: "5Gi"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: onRootMismatch
    additionalVolumeMounts:
    - name: media-nas
      mountPath: "/media"
    additionalVolumes:
    - name: media-nas
      persistentVolumeClaim:
        claimName: media-nfs-share-pvc
