---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media 
spec:
  interval: 5m
  chart:
    spec:
      chart: lidarr
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v0.8.0.2075
    env:
      TZ: "Europe/Brussels"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: letsencrypt 
      hosts:
      - host: lidarr.lab.kharnox.xyz
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - lidarr.lab.kharnox.xyz
        secretName: lidarr-tls
    persistence:
      config:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: "20Gi"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    additionalVolumeMounts:
    - name: media-nas
      mountPath: "/media"
    additionalVolumes:
    - name: media-nas
      persistentVolumeClaim:
        claimName: media-nfs-share-pvc
