---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: coredns
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    rbac:
      create: true
    replicaCount: 1
    isClusterService: true 
    serviceType: LoadBalancer
    service:
      externalIPs:
      - 10.0.1.5
      externalTrafficPolicy: Local
    servers:
    - zones:
      - zone: lab.kharnox.xyz
        scheme: dns://
        # use_tcp: true
      port: 53
      plugins:
      - name: log
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . 10.0.1.4
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: etcd
        parameters: devbu.io
        configBlock: |-
          stubzones
          path /skydns
          endpoint http://etcd:2379
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
