---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              cpu: 1000m
              #memory: 1Gi
            requests:
              cpu: 50m
              #memory: 64Mi