---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-helm-repositories
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./cluster/flux-system/helmrepo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
