apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10s
  url: https://github.com/kharnox/k8s-homelab
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include cluster directory
    !/cluster/
