---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: master
  url: https://github.com/kharnox/k8s-homelab

