---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: monitoring 
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
  interval: 10m0s
  values:
    controllerType: deployment
    image:
      repository: docker.io/falcosecurity/falco
      tag: 0.27.0

