---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: flux-system
spec: 
  interval: 10m
  url: https://falcosecurity.github.io/charts 
  timeout: 3m
